// User
export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_ERRORS = 'SET_ERRORS'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const EDIT_PROFILE = 'EDIT_PROFILE'

// Data
export const DATA_LOADING = 'DATA_LOADING'
export const SET_AVAILABLE_HOSTEL = 'SET_AVAILABLE_HOSTEL'
export const SET_SINGLE_HOSTEL_DETAIL = 'SET_SINGLE_HOSTEL_DETAIL'
export const BOOKING = 'BOOKING'
export const CANCEL_BOOKING = 'CANCEL_BOOKING'
export const SET_BOOKING_LIST = 'SET_BOOKING_LIST'
export const SET_OWN_HOSTEL = 'SET_OWN_HOSTEL'
export const DELETE_HOSTEL = 'DELETE_HOSTEL'
export const SET_HOSTEL_STATUS = 'SET_HOSTEL_STATUS'
export const ADD_HOSTEL = 'ADD_HOSTEL'
export const EDIT_HOSTEL = 'EDIT_HOSTEL'
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA'
export const RATING = 'RATING'

// Admin
export const SET_ALL_HOSTEL_LIST = 'SET_ALL_HOSTEL_LIST'
export const APPROVE_REQUEST = 'APPROVE_REQUEST'